name: Deploy APK Repo to GitHub Pages

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: [self-hosted]

    strategy:
      matrix:
        include:
          - branch: stable
            publish_branch: gh-pages

    if: github.ref == 'refs/heads/stable' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy APKINDEX files for deployment
        run: |
          mkdir -p public/x86_64
          cp -r x86_64/*.apk x86_64/APKINDEX.tar.gz* public/x86_64/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ matrix.publish_branch }}
          publish_dir: ./public
          keep_files: true

